### ISSUE TITLE
CSV data cannot be exported with a comma in its entry

### ISSUE THREAD

**Issue by Aravind-Ram-321** [jameskokoska/Cashew#300]
**Describe your question**
I'm trying to export a set of transactions from my one account to another account. I used the export CSV file but the issue is the string after comma in my transaction titles are deleted in the CSV file. For example, if my transaction title is "Apple, Banana @ X supermarket", I only see "Apple" in the CSV file. I have a lot of transactions like this where I have used commas generously. Please help me with a solution.

**Comment by ngocanhtve** [comment]
Export data file instead of csv file.

**Comment by Aravind-Ram-321** [comment]
> Export data file instead of csv file.

But how do I import it into my other account? If I do import, it will overwrite on top of all the existing transaction in my 2nd account, right? I only want to import a certain set of transaction let's say for the past two months into my 2nd account.

**Comment by jameskokoska** [comment]
Has been fixed here: https://github.com/jameskokoska/Cashew/commit/150fa04c3bdabccaeb756dfd50e9c00828ec2c17

**Comment by jameskokoska** [comment]
> I'm trying to export a set of transactions from my one account to another account. 

Just an aside, to import your transactions into another account, you can do this all within the app. Edit the account you want to transfer transactions out of, and use the "Merge Account" feature. Select the account you want to transfer transactions into.
![image](https://github.com/jameskokoska/Cashew/assets/50821962/a8f0b362-c195-4c86-af64-6477ab97b8eb)

**Comment by Aravind-Ram-321** [comment]
> Edit the account you want to transfer transactions out of, and use the "Merge Account" feature. Select the account you want to transfer transactions into.

Hey, I'm sorry. I should have been more clear. When I said accounts, I meant two different user accounts with different gmail ids, not the currency accounts within the app. So, I'm trying to export my past two-month txns from one gmail account to another gmail account.

Also, I tried exporting the CSV file now and it's still the same issue. String after comma is getting truncated still.
![Screenshot 2024-06-17 125009](https://github.com/jameskokoska/Cashew/assets/164659065/ff46967c-3c47-4d56-baf8-b6bd1a7b980f)

![Screenshot 2024-06-17 124805](https://github.com/jameskokoska/Cashew/assets/164659065/677c3894-d485-43f1-b5ae-ff1bfa13b98b)

**Comment by Aravind-Ram-321** [comment]
Hi @jameskokoska, could you please check this again?

**Comment by jameskokoska** [comment]
Yes it has been fixed in commit https://github.com/jameskokoska/Cashew/commit/f7fca04baa1bec53422b296f555fac9dd538926b

**Comment by Aravind-Ram-321** [comment]
> Yes it has been fixed in commit [f7fca04](https://github.com/jameskokoska/Cashew/commit/f7fca04baa1bec53422b296f555fac9dd538926b)

But I'm still getting the same issue. Could you please check my last two screenshots above?
@jameskokoska

**Comment by jameskokoska** [comment]
Please make sure you are running the latest commit, version 5.3.2+384 and higher
Note this has not yet been released on the Play Store, App Store, or on GitHub.
