### ISSUE TITLE
[Bug] "Save changes" button inactive after adding/removing a title to "Associated Titles" section of Category

### ISSUE THREAD

**Issue by shitcoding** [jameskokoska/Cashew#305]
**Describe the bug**
After adding/removing some title to category's "Associated Titles" section (that should be automatically added to this category), "Save Changes" button remains inactive.
I need to edit category name or color, only after that "Save Changes" button becomes active and I can save the category.

**How to reproduce**
- Select some category
- Add or remove one or more "Associated Titles"
- Try to save the category

**Details**
 - Device: Android and web app
 - App Version: v5.3.1+379

**Comment by jameskokoska** [comment]
This has been already fixed here: https://github.com/jameskokoska/Cashew/commit/d47986275207531f9c3d4339a9b1c2745b8ca7b6

**Comment by shitcoding** [comment]
Umm this is weird, I just tested it both in web app and on Android, and both this and [this](https://github.com/jameskokoska/Cashew/issues/306) bug are still there. App version is v5.3.1+379
Android app is updated to the latest version, web app should be always up to date.

What am I doing wrong?:)

**Comment by jameskokoska** [comment]
In the linked commit you can see the version is `5.3.2+387` which hasn't been released yet.

**Comment by shitcoding** [comment]
Got it, thank you!
