### ISSUE TITLE
Copied Transfer Transactions Are Still Linked to the Original Ones

### ISSUE THREAD

**Issue by Michael152843** [jameskokoska/Cashew#421]
**Describe the bug**
There is an issue when you copy transfer transactions - the newly created pair of transactions (Transfer Out and Transfer In) is still somehow linked to the original, and if you update the new Transfer Out transaction and select "Update both", it will also update the original Transfer In. Also, if you decide to change the time of the new pair of transactions, then the Transfer In transaction unlinks both from the original and from the copy.

**How to reproduce**
Create transfer transactions then copy them and try to update the amount of the newly created pair of transactions.

**Details**
 - Device: Android
 - App Version: 5.4.1+411

**Comment by jameskokoska** [comment]
Fixed here: https://github.com/jameskokoska/Cashew/commit/e530625d5c9f5a5bd20695815ceef69f24c3e23d

**Comment by Michael152843** [comment]
It seems like the issue is still there. Now that we can group transfer transactions it is even more obvious. 

To reproduce: create a pair of transfer transactions > copy them to current time. The new transaction pair is unlinked and updating the Transfer Out transaction also "breaks" the link of the original pair.

**Comment by jameskokoska** [comment]
Will look into this further.
