### ISSUE TITLE
[Bug] Uneven number width

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#834]
**Describe the bug**
On the home screen, the width of the numbers is uneven, even the amount of the transactions.

**How to reproduce**
As can be seen everywhere, the width of the number 0 is the widest, the numbers 5 and 7 are a little narrower, and the number 1 is the narrowest.

**Screenshots/videos**
![Image](https://github.com/user-attachments/assets/451184af-e3c2-4384-a2f6-45ffe835c483)

**Details**
 - Device: OnePlus 13
 - App Version: 6.0.9 (Beta PlayStore)

**Additional notes**
Notice that the decimal separator (dot) is not on the same vertical line, which shows that the numbers between the horizontal rows are not evenly spaced. As far as I know, on some platforms, whether it's a 1 or a 0, they're evenly spaced and have the same width, which gives a nice design balance. Which I think should apply to Cashew as well.

**Comment by jameskokoska** [comment]
The width of the numbers is dependent on the selected font. The default font in Cashew has monospaced numbers, but others may not.

**Comment by ngocanhtve** [comment]
Cashew's default font does not support Vietnamese, resulting in font display errors. So I chose the display font following to the platform font. Looks like there needs to be a feature to make Android system fonts display numbers as evenly width.

**Comment by jameskokoska** [comment]
Cashew’s default font, and all other fonts in Cashew have a fallback font to catch any missing characters within the selected font. Does this not work as expected?

**Comment by ngocanhtve** [comment]
You know, when a language is not supported by a font, the missing characters will be displayed using a different font. This makes the text visually difficult to read, since each word may appear in two different font styles instead of one uniform style. For someone with OCD like me, it’s easy to feel dizzy when looking at such text.

**Comment by jameskokoska** [comment]
This has been fixed in the latest beta. Fonts heights have been adjusted and the fallback font is applied to all languages across all fonts.
If this is still an active issue, add an update and this ticket can be further discussed and reopened as necessary. See #725 for Beta Testing instructions and information.

**Comment by ngocanhtve** [comment]
This issue is **still present**.

My device is using **Android system default font** (no custom font), and in Cashew the numbers are still **uneven width** and the **decimal separator** is still **mis-aligned** across rows.

Device: OnePlus 13  
OS: Android 15  
App language: Vietnamese (VN uses `.` for thousand and `,` for decimal)

**Comment by jameskokoska** [comment]
Not all fonts (including the ones provided in Cashew) have monospaced numbers. The vertical offset of the fallback font was adjusted so that if the selected font doesn’t have a certain character, another fallback font will vertically align so it can be used as the font for those characters.
