### ISSUE TITLE
[Question] How to reduce Budget with negative expense/ income on expense category?

### ISSUE THREAD

**Issue by a-johanes** [jameskokoska/Cashew#963]
**Describe your question**
Let's say I have a monthly Expense Budget, and I set Shopping category to have a limit of $100. One day I buy a $100 worth of stuff, I paid for it all but this supposed to be shared equally with one of my friend. In this case I want to have 1 transaction in Shopping for spending of $100, but I only want to record $50 to my budget and $50 to either another Loan account or using the Loan Transaction Type.

On my current money manager, I can put negative expense, which seems like not working here. Another approach in another app is to offset the Expense Budget with Income value of Expense Category. For example, in this case I still record the $100 Shopping expense. Then I make another Income transaction of $50 for Shopping (Shopping is Expense Category) and maybe also set the Transaction Type to Loan. Or this can also be achieved using Transfer Shopping to My-Loan-Category.

I don't know if such a feature/option/setting existed or not, so I put it under question first. Kindly let me know if I need to open another ticket for feature request.

NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating questions. Duplicates will not be addressed again.**
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by jameskokoska** [comment]
Related to https://github.com/jameskokoska/Cashew/issues/18

This is already addressed in the FAQ here: https://cashewapp.web.app/faq.html#budget-filters

You can choose to include/exclude loans or income transactions in an “All Transactions” budget by editing the budget.

**Comment by a-johanes** [comment]
Hi, thank you for the prompt answer. It seems I am still missing some points in the FAQ. I will check out more of it.
