### ISSUE TITLE
[Bug] Negative value on google sheet not considered when creating transaction from Inbox

### ISSUE THREAD

**Issue by a-johanes** [jameskokoska/Cashew#970]
**Describe the bug**
When using the beta feature for Inbox,  the sign in the amount is not considered for created transaction type. Seems like it is following the Category type instead. 

**How to reproduce**
1. Add a positive amount transaction on Google Sheet with Expense Category
2. Open Inbox in app
3. Transaction suggested is expense. Expected to be Income type, similar with how import CSV works.

Also happened for negative value on Income Category, will create Income type regardless if the amount is negative or positive.

**Screenshots/videos**
![Screenshot_20251228_211758_Sheets.jpg](https://github.com/user-attachments/assets/22af066b-deab-4f60-b504-d932e474343a)

![Screenshot_20251228_211810.jpg](https://github.com/user-attachments/assets/fb939be6-0828-4d04-9b8d-70ed1c41bdb3)

**Details**
 - Device: Samsung S21 FE 5G
 - App Version: 6.2.4 beta from Google Play

**Additional notes**
NA

NOTE TO THE SUBMITTER
Reporting bugs is important for maintaining the app. Thank you for helping make the app a better experience for all!

**Comment by GitAritron** [comment]
The same bug is also present when you add transactions using App Links with json.
(I have a workflow that automated transfers between accounts with the Balance Correction category, and now both transactions (in and out) appear as expense.

**Comment by jameskokoska** [comment]
This has been addressed in the latest beta (6.2.7+470)
The inbox import has been fixed to allow for expense and income based on the +/- sign.
If this is still an active issue, add an update and this ticket can be further discussed and reopened as necessary. See #725 for Beta Testing instructions and information.

**Comment by GitAritron** [comment]
I just want to note that the issue is still present in JSON transactions. Version is 6.5.9

**Comment by jameskokoska** [comment]
> I just want to note that the issue is still present in JSON transactions. Version is 6.5.9

I wasn't able to replicate this issue - could you let me know an example so I can reproduce it?

**Comment by GitAritron** [comment]
Yes, of course.

The JSON is this:
{"transactions":[{"amount":"-0.01","title":"Transfer Out","category":"Balance","account":"AccountOut"},{"amount":"0.01","title":"Transfer In","category":"Balance","account":"AccountIn"}]}
It is encoded to: %7B%22transactions%22%3A%5B%7B%22amount%22%3A%22-0.01%22%2C%22title%22%3A%22Transfer+Out%22%2C%22category%22%3A%22Balance%22%2C%22account%22%3A%22AccountOut%22%7D%2C%7B%22amount%22%3A%220.01%22%2C%22title%22%3A%22Transfer+In%22%2C%22category%22%3A%22Balance%22%2C%22account%22%3A%22AccountIn%22%7D%5D%7D

I tired to minimize it as much as possible.


I'm not sure in which version exactly the behaviour changed (probably around at the time of the opening of this thread), but it used to work as intended just like a manual transfer transaction would: subtract from one account add to another.
Then it changed to default of category (regardless of sign in the amount - tried with both "-" and "+")

And the result is this: (two negative transactions)
<img width="594" height="330" alt="Image" src="https://github.com/user-attachments/assets/b4eaaa4d-0595-4893-8117-f7f6cbd3fac2" />

**Comment by jameskokoska** [comment]
It appears to be working as expected on my end - the polarity of the category is used because the parameter `categoryPolarity` isn’t set to false. If that is set to false, you will be able to specify the amount polarity in the amount field directly. You can review the documentation here: https://cashewapp.web.app/faq.html#app-links

**Comment by GitAritron** [comment]
I see, that's something new - I haven't seen it in the documentation before.
I guess when it was added the chosen default became the opposite of the previous behaviour...

Thank you for the tip, I didn't know there were changes to the docs, otherwise I would have checked there first. 
Thank you for the great work you are doing!

**Comment by jameskokoska** [comment]
No worries! It's hard to announce breaking behavior changes to only the users who use App Links regularly. Additionally, most development of new features and changes tries to ensure no breaking changes to the default behavior - however in this case it was unavoidable. Glad its all solved!
